### PR TITLE
Add option for three sizes of placeholder images to ipsum parameter

### PR DESCRIPTION
**Pull request by ThisIsJohnBrown**
Love schematic-ipsum for generating my test JSON.

Saw issue #3 and it seems like a good idea. I added it to the ipsum parameter, since it's a URL string.

Since you're going for randomized text to give the data a "lived in" feel, I used hhhhold.com because it delivers slightly randomized content, and not just the same static image to each instance like placehold.it would.

### CODE REVIEW

**Comment by jonahkagan** [comment]
Awesome! This looks cool. hhhhold seems like a good choice. Do you think you could add in a test for each of the new ipsum parameters? I know the testing for ipsum parameters isn't very good yet, but it's good to make sure they at least produce something. Also, could you modify the documentation to include the new params?

**Comment by ThisIsJohnBrown** [comment]
Can do. I will resubmit the pull request tonight.

Sorry I forgot about the tests! I always do.

**Comment by ThisIsJohnBrown** [comment]
Made that update and added tests. All went according to plan.

Added the options to the documentation. I was going to add an "avatar" option to your example you walked through at the top, but figured I would check with you and see if you wanted that.

**Comment by jonahkagan** [comment]
Looks good. Adding an avatar to the example sounds cool -- go for it. I was a bit confused by `URL for an image with both dimensions between 100px and 250px`. How about just stealing the text from hhhhold? `URL for an image with width and height both randomly between 100px and 250px`.

**Comment by ThisIsJohnBrown** [comment]
Done and done.

**Comment by jonahkagan** [comment]
Coolio. I made a few tiny tweaks and rebased/merged it in as one commit. (I haven't actually ever done this before, so it might be a little messy :smile:).  Thanks for the contribution!

**Comment by ThisIsJohnBrown** [comment]
Thanks for letting me help!

**Pull request closed without merging**
